name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Run unit tests
        run: dart test tests/unit
      - name: Run integration tests
        run: dart test tests/integration
